[
    {
        "id": "flow_methane_sim",
        "type": "tab",
        "label": "Methane -> Weaviate (direct)",
        "disabled": false,
        "info": "Simulates methane readings and POSTS directly to Weaviate /v1/objects"
    },
    {
        "id": "inject_trigger",
        "type": "inject",
        "z": "flow_methane_sim",
        "name": "Trigger (every 10s)",
        "props": [{"p":"payload"}],
        "repeat": "10",
        "once": true,
        "onceDelay": "1",
        "topic": "",
        "payloadType": "date",
        "x": 180,
        "y": 120,
        "wires": [["fn_generate"]]
    },
    {
        "id": "fn_generate",
        "type": "function",
        "z": "flow_methane_sim",
        "name": "Create Weaviate object payload",
        "func": "// Build a valid Weaviate object for SensorEvent\n// You can also replace node_id with msg.payload.node_id to accept external input\nlet methane = parseFloat((Math.random() * 90 + 10).toFixed(2));\n\nmsg.payload = {\n  class: \"SensorEvent\",\n  properties: {\n    node_id: \"CH4_001\",\n    methane_ppm: methane,\n    timestamp: new Date().toISOString(),\n    scenario: methane > 80 ? \"alert\" : \"normal\",\n    trace_id: \"trace-\" + Date.now()\n  }\n};\n\n// Debug-friendly summary\nmsg.summary = {\n  node_id: msg.payload.properties.node_id,\n  methane_ppm: msg.payload.properties.methane_ppm,\n  timestamp: msg.payload.properties.timestamp\n};\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 440,
        "y": 120,
        "wires": [["http_post", "debug_generated"]]
    },
    {
        "id": "http_post",
        "type": "http request",
        "z": "flow_methane_sim",
        "name": "POST -> Weaviate /v1/objects",
        "method": "POST",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://127.0.0.1:8080/v1/objects",
        "timeout": "10",
        "tls": "",
        "persist": false,
        "proxy": "",
        "authType": "",
        "headers": {"Content-Type":"application/json"},
        "x": 740,
        "y": 120,
        "wires": [["debug_weaviate_response","debug_payload"]]
    },
    {
        "id": "debug_generated",
        "type": "debug",
        "z": "flow_methane_sim",
        "name": "Generated payload summary",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "summary",
        "targetType": "msg",
        "x": 680,
        "y": 60,
        "wires": []
    },
    {
        "id": "debug_payload",
        "type": "debug",
        "z": "flow_methane_sim",
        "name": "Full payload (to send)",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "x": 940,
        "y": 60,
        "wires": []
    },
    {
        "id": "debug_weaviate_response",
        "type": "debug",
        "z": "flow_methane_sim",
        "name": "Weaviate Response",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "x": 940,
        "y": 140,
        "wires": []
    }
]
