[
  {
    "id": "flow_methane_control",
    "type": "tab",
    "label": "Methane Simulation with Stop & Resume",
    "disabled": false,
    "info": "Simulates methane readings (1000–5000 ppm), injects breach >5000 every 5 min, and supports manual stop/resume."
  },
  {
    "id": "inject_auto",
    "type": "inject",
    "z": "flow_methane_control",
    "name": "⏱ Auto Trigger (every 15s)",
    "props": [{"p":"payload"}],
    "repeat": "15",
    "crontab": "",
    "once": true,
    "onceDelay": "1",
    "topic": "",
    "payload": "",
    "payloadType": "date",
    "x": 180,
    "y": 120,
    "wires": [["fn_generate"]]
  },
  {
    "id": "inject_stop",
    "type": "inject",
    "z": "flow_methane_control",
    "name": "🛑 Manual Stop Button",
    "props": [{"p":"payload"},{"p":"topic","vt":"str"}],
    "repeat": "",
    "crontab": "",
    "once": false,
    "onceDelay": 0.1,
    "topic": "",
    "payload": "stop",
    "payloadType": "str",
    "x": 180,
    "y": 180,
    "wires": [["fn_stop"]]
  },
  {
    "id": "fn_stop",
    "type": "function",
    "z": "flow_methane_control",
    "name": "Stop Flow Handler",
    "func": "flow.set('stopFlow', true);\nnode.status({fill:'red', shape:'ring', text:'Flow stopped manually'});\nreturn null;",
    "outputs": 0,
    "noerr": 0,
    "x": 440,
    "y": 180,
    "wires": []
  },
  {
    "id": "inject_resume",
    "type": "inject",
    "z": "flow_methane_control",
    "name": "🟢 Resume Flow Button",
    "props": [{"p":"payload"},{"p":"topic","vt":"str"}],
    "repeat": "",
    "crontab": "",
    "once": false,
    "onceDelay": 0.1,
    "topic": "",
    "payload": "resume",
    "payloadType": "str",
    "x": 190,
    "y": 240,
    "wires": [["fn_resume"]]
  },
  {
    "id": "fn_resume",
    "type": "function",
    "z": "flow_methane_control",
    "name": "Resume Flow Handler",
    "func": "flow.set('stopFlow', false);\nnode.status({fill:'green', shape:'dot', text:'Flow resumed'});\nreturn null;",
    "outputs": 0,
    "noerr": 0,
    "x": 440,
    "y": 240,
    "wires": []
  },
  {
    "id": "fn_generate",
    "type": "function",
    "z": "flow_methane_control",
    "name": "Generate Methane Reading",
    "func": "// Skip if manually stopped\nif (flow.get('stopFlow')) {\n    node.status({fill:'red', shape:'dot', text:'Stopped'});\n    return null;\n}\n\nconst lastBreach = flow.get('lastBreach') || 0;\nconst now = Date.now();\n\nlet methane_ppm;\nlet scenario = 'normal';\n\n// Trigger anomaly every 5 minutes (300000 ms)\nif (now - lastBreach >= 300000) {\n    methane_ppm = parseFloat((Math.random() * 1500 + 5000).toFixed(2)); // 5000–6500 ppm\n    scenario = 'breach';\n    flow.set('lastBreach', now);\n} else {\n    methane_ppm = parseFloat((Math.random() * 4000 + 1000).toFixed(2)); // 1000–5000 ppm\n}\n\nmsg.payload = {\n    class: \"SensorEvent\",\n    properties: {\n        node_id: \"CH4_001\",\n        methane_ppm: methane_ppm,\n        timestamp: new Date().toISOString(),\n        scenario: scenario,\n        trace_id: \"trace-\" + Date.now()\n    }\n};\n\nmsg.summary = {\n    node_id: msg.payload.properties.node_id,\n    methane_ppm: methane_ppm,\n    scenario: scenario,\n    timestamp: msg.payload.properties.timestamp\n};\n\nnode.status({fill:'green', shape:'dot', text:`${scenario.toUpperCase()} ${methane_ppm} ppm`});\nreturn msg;",
    "outputs": 1,
    "noerr": 0,
    "x": 470,
    "y": 120,
    "wires": [["http_weaviate","debug_summary"]]
  },
  {
    "id": "http_weaviate",
    "type": "http request",
    "z": "flow_methane_control",
    "name": "POST → Weaviate /v1/objects",
    "method": "POST",
    "ret": "txt",
    "paytoqs": "ignore",
    "url": "http://127.0.0.1:8080/v1/objects",
    "tls": "",
    "persist": false,
    "proxy": "",
    "authType": "",
    "headers": {"Content-Type":"application/json"},
    "x": 800,
    "y": 120,
    "wires": [["debug_response"]]
  },
  {
    "id": "debug_summary",
    "type": "debug",
    "z": "flow_methane_control",
    "name": "Generated Reading Summary",
    "active": true,
    "tosidebar": true,
    "console": false,
    "tostatus": false,
    "complete": "summary",
    "targetType": "msg",
    "x": 830,
    "y": 70,
    "wires": []
  },
  {
    "id": "debug_response",
    "type": "debug",
    "z": "flow_methane_control",
    "name": "Weaviate Response",
    "active": true,
    "tosidebar": true,
    "console": false,
    "tostatus": false,
    "complete": "payload",
    "targetType": "msg",
    "x": 1080,
    "y": 120,
    "wires": []
  }
]
